**Postgrado en Ciencias de la Computación**  
**Inteligencia Artificial (CC6021236)**  
**Semestre 2019-1**  
**Prof. Eugenio Scalise**  

## Tarea 4 (Aprendizaje No Supervizado - Agrupamiento/Clustering)

***(inserte sus datos personales en esta celda)***

En esta tarea se utilizará un set de datos con información de uso de tarjetas de crédito durante 6 meses. El objetivo es utilizar técnicas de agrupamiento/clustering (y si lo considera necesario, reducción de dimensionalidad con PCA) para hacer una segmentación de usuarios.

El dataset está desplegado en este [URL en el repositorio de la materia](https://raw.githubusercontent.com/escalise/AI_Course_PG/master/assignments/cc_data.csv) y también hay un pequeño [diccionario de datos](https://raw.githubusercontent.com/escalise/AI_Course_PG/master/assignments/cc_data_dict.txt).

In [1]:
# lectura del dataset como un DataFrame en Pandas
import pandas as pd

url ="https://raw.githubusercontent.com/escalise/AI_Course_PG/master/assignments/cc_data.csv"
data = pd.read_csv(url)

print(data.shape)
data.head(10)

(8950, 18)

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,C10001,40.900749,0.818182,95.40,0.00,95.40,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12
1,C10002,3202.467416,0.909091,0.00,0.00,0.00,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12
2,C10003,2495.148862,1.000000,773.17,773.17,0.00,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.00,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,NaN,0.000000,12
4,C10005,817.714335,1.000000,16.00,16.00,0.00,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12
5,C10006,1809.828751,1.000000,1333.28,0.00,1333.28,0.000000,0.666667,0.000000,0.583333,0.000000,0,8,1800.0,1400.057770,2407.246035,0.000000,12
6,C10007,627.260806,1.000000,7091.01,6402.63,688.38,0.000000,1.000000,1.000000,1.000000,0.000000,0,64,13500.0,6354.314328,198.065894,1.000000,12
7,C10008,1823.652743,1.000000,436.20,0.00,436.20,0.000000,1.000000,0.000000,1.000000,0.000000,0,12,2300.0,679.065082,532.033990,0.000000,12
8,C10009,1014.926473,1.000000,861.49,661.49,200.00,0.000000,0.333333,0.083333,0.250000,0.000000,0,5,7000.0,688.278568,311.963409,0.000000,12
9,C10010,152.225975,0.545455,1281.60,1281.60,0.00,0.000000,0.166667,0.166667,0.000000,0.000000,0,3,11000.0,1164.770591,100.302262,0.000000,12

In [2]:
# información estadística de las características
data.describe()

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
count,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8949.000000,8950.000000,8637.000000,8950.000000,8950.000000
mean,1564.474828,0.877271,1003.204834,592.437371,411.067645,978.871112,0.490351,0.202458,0.364437,0.135144,3.248827,14.709832,4494.449450,1733.143852,864.206542,0.153715,11.517318
std,2081.531879,0.236904,2136.634782,1659.887917,904.338115,2097.163877,0.401371,0.298336,0.397448,0.200121,6.824647,24.857649,3638.815725,2895.063757,2372.446607,0.292499,1.338331
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.019163,0.000000,6.000000
25%,128.281915,0.888889,39.635000,0.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,1.000000,1600.000000,383.276166,169.123707,0.000000,12.000000
50%,873.385231,1.000000,361.280000,38.000000,89.000000,0.000000,0.500000,0.083333,0.166667,0.000000,0.000000,7.000000,3000.000000,856.901546,312.343947,0.000000,12.000000
75%,2054.140036,1.000000,1110.130000,577.405000,468.637500,1113.821139,0.916667,0.300000,0.750000,0.222222,4.000000,17.000000,6500.000000,1901.134317,825.485459,0.142857,12.000000
max,19043.138560,1.000000,49039.570000,40761.250000,22500.000000,47137.211760,1.000000,1.000000,1.000000,1.500000,123.000000,358.000000,30000.000000,50721.483360,76406.207520,1.000000,12.000000

Documente en este notebook (con código, gráficas y análisis) las siguientes actividades:

1. Realice los preprocesamientos y visualizaciones de las características de los datos que permitan tener una idea de los posibles clusters de usuarios a identificar.

2. Utilice la técnica de k-medias (K-means) para realizar un modelo de agrupamiento. Adicionalmente, utilice la técnica del "codo" (elbow) para determinar un valor razonable para K. En el [Piazza del curso](https://piazza.com/universidad_central_de_venezuela/spring2019/cc6021236/resources) se agregó un [artículo que describe el "Elbow Method"](https://blog.cambridgespark.com/how-to-determine-the-optimal-number-of-clusters-for-k-means-clustering-14f27070048f).

3. Utilice ahora clustering jerárquico (Hierarchical Clustering) con los criterios de "linkage" mencionados en clase (ward, single, complete y average) y compare los resultados.

4. Concluya sobre los resultados obtenidos.

### Consideraciones:  

- Utilice una copia de este Jupyter Notebook usando Python3 para hacer el proyecto.
- Renombre el documento como `Tarea_4_-_Nombre1_Apellido1_-_Nombre2_Apellido2.ipynb`
- Agregue todas las celdas necesarias tanto de código como markdown para que el desarrollo de cada pregunta sea fácil de leer y entender. 
- Agregue una celda de referencias y cite **todo** recurso que utilice. Utilice formato IEEE para las referencias.
- Esta tarea se puede realizar en grupos de dos personas.
- Para la entrega, hospede su solución en http://colab.research.google.com. La fecha y hora de la última modificación del documento será considerada el *timestamp* de entrega. Para mayor seguridad, envíe también el notebook como una anexo por correo a `escalise at gmail dot com`.
- Todas las celdas de código de la entrega deben estar ejecutadas para facilitar la corrección.
- La fecha de entrega de esta tarea es el domingo 03/11/2019, 11:59:59 PM (VET time).